all:
  sf_captchagd:
     image_width:                90 # image width in pixels
     image_height:               30 # image height in pixels
     chars:                      "2345678abcdefhjkmnprsuxyz" # possible chars in captcha
     length:                     2 # length of captcha
     font_size:                  20 # font size
     force_new_captcha:          true # if true - captcha regenerated EVERY request, even if user input true value before
     fonts: ["akbar/vavobi.ttf"]

  image_maxsize: 52428800
  upload_max_size:   104857600
  image_upload_max_size: 52428800
  upload_video_max_size: 50485760
  upload_max_size:   104857600
  excel_max_row: 1000
  category_images: category_images
  article_images: article
  service_images: service
  advertise_images: advertise
  product_images: products
  import_max_size: 1048576
  album_images: album
  video_images: video
  document: document
  member_images: member
  image_default: 'http://nehobcity.com/images/default.jpg'
  upload_media_file: "E:\app\project\dungbq3\xnk\xnk\web\uploads"
  url_media_file: http://localhost:9763/uploads
  url_media_default_file: http://localhost:9763/images/default-image.jpg
  image_default: http://localhost:9763/images/default-image.jpg
  #upload_media_file: /uploads

  url_media_file: /uploads
  
  ckeditor:
    basePath: /js/ckeditor
  ckfinder:
    active: true
    basePath: /js/ckfinder
  addcslashes_charlist: "%_-\'"  # Danh sach cac ky tu dac biet can xu ly truoc khi su dung search query
  seo:
    title: 'XNK'
    description: 'Tủ bếp Hoàn Mỹ chuyên cung cấp Bếp điện từ, bếp gas âm, máy hút mùi, máy rửa bát, máy sấy, máy lọc nước, lò nướng, lò vi sóng, chậu rửa bát, đồ gia dụng, thiết bị vệ sinh'
    keywords: 'Bếp điện từ, bếp gas âm, máy hút mùi, máy rửa bát, máy sấy, máy lọc nước, lò nướng, lò vi sóng, chậu rửa bát, đồ gia dụng, thiết bị vệ sinh'
    ogImage: ''
    url: 'http://tubephoanmy.com'
  ManageAdChainImage:
    maxsize: 999999
    prefix: 'chain'
    type: 'image/jpeg|image/jpg|image/png|image/gif'